codP1, numP1, valueP1 = input().split()
codP2, numP2, valueP2 = input().split()
codP1 = int(codP1)
numP1 = int(numP1)
valueP1 = round(float(valueP1), 2)
codP2 = int(codP2)
numP2 = int(numP2)
valueP2 = round(float(valueP2), 2)
result = (numP1 * valueP1) + (numP2 * valueP2)
print(f'VALOR A PAGAR: R$ {result:.2f}')